import { Ticket, ActivityItem, User } from '../types';

export const DEMO_USERS: User[] = [
  {
    id: 'usr_admin_1',
    name: 'Marcus Sterling',
    email: 'marcus@resolvehq.internal',
    role: 'admin',
    department: 'IT Infrastructure',
    jobTitle: 'VP of IT Operations',
    createdAt: '2026-01-15T08:00:00Z',
  },
  {
    id: 'usr_agent_1',
    name: 'Sarah Chen',
    email: 'sarah.chen@resolvehq.internal',
    role: 'agent',
    department: 'Tier-2 Support',
    jobTitle: 'Senior Systems Specialist',
    createdAt: '2026-02-01T09:30:00Z',
  },
  {
    id: 'usr_agent_2',
    name: 'Alex Rivera',
    email: 'alex.rivera@resolvehq.internal',
    role: 'agent',
    department: 'Network Operations',
    jobTitle: 'Network & Security Engineer',
    createdAt: '2026-02-10T10:15:00Z',
  },
  {
    id: 'usr_emp_1',
    name: 'Elena Rostova',
    email: 'elena.rostova@acmecorp.com',
    role: 'employee',
    department: 'Product Design',
    jobTitle: 'Lead Product Designer',
    createdAt: '2026-03-01T11:00:00Z',
  },
  {
    id: 'usr_emp_2',
    name: 'David Kim',
    email: 'david.kim@acmecorp.com',
    role: 'employee',
    department: 'Engineering',
    jobTitle: 'Staff Backend Engineer',
    createdAt: '2026-03-12T14:20:00Z',
  },
];

// Production queue clean slate: starts empty so user can create live demo tickets
export const INITIAL_TICKETS: Ticket[] = [];

// Landing page interactive mini-demo preview tickets
export const LANDING_DEMO_TICKETS: Ticket[] = [
  {
    id: 'demo-tkt-1',
    ticketNumber: 'RHQ-1082',
    title: 'PostgreSQL read replica replication lag exceeding 450s',
    description: 'The production secondary node in us-east-1 is failing to keep up with write bursts. Cache invalidations are timing out during burst hours.',
    status: 'in_progress',
    priority: 'urgent',
    category: 'network',
    creatorId: 'usr_emp_2',
    creatorName: 'David Kim',
    creatorEmail: 'david.kim@acmecorp.com',
    assigneeId: 'usr_agent_2',
    assigneeName: 'Alex Rivera',
    slaDueHours: 4,
    slaDeadline: new Date(Date.now() + 2 * 3600 * 1000).toISOString(),
    isOverdue: false,
    createdAt: new Date(Date.now() - 3.5 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    commentsCount: 3,
  },
  {
    id: 'demo-tkt-2',
    ticketNumber: 'RHQ-1081',
    title: 'VPN certificate auto-renewal failed on macOS Sequoia workstations',
    description: 'Multiple staff members reported TLS handshake failure when attempting remote gateway sign-in via WireGuard client configuration.',
    status: 'open',
    priority: 'high',
    category: 'security',
    creatorId: 'usr_emp_1',
    creatorName: 'Elena Rostova',
    creatorEmail: 'elena.rostova@acmecorp.com',
    assigneeId: 'usr_agent_1',
    assigneeName: 'Sarah Chen',
    slaDueHours: 8,
    slaDeadline: new Date(Date.now() + 5 * 3600 * 1000).toISOString(),
    isOverdue: false,
    createdAt: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    commentsCount: 2,
  },
  {
    id: 'demo-tkt-3',
    ticketNumber: 'RHQ-1080',
    title: 'Provision developer laptop & Okta SSO for incoming Senior FE Engineer',
    description: 'New hire onboarding package required: MacBook Pro M4 36GB, YubiKey 5C NFC, and Google Workspace security provisioning for starting date Monday.',
    status: 'in_progress',
    priority: 'medium',
    category: 'hardware',
    creatorId: 'usr_admin_1',
    creatorName: 'Marcus Sterling',
    creatorEmail: 'marcus@resolvehq.internal',
    assigneeId: 'usr_agent_1',
    assigneeName: 'Sarah Chen',
    slaDueHours: 24,
    slaDeadline: new Date(Date.now() + 18 * 3600 * 1000).toISOString(),
    isOverdue: false,
    createdAt: new Date(Date.now() - 8 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    commentsCount: 2,
  },
  {
    id: 'demo-tkt-4',
    ticketNumber: 'RHQ-1079',
    title: 'Figma Enterprise workspace billing seats sync error',
    description: 'SSO SCIM provisioning threw error 429 when syncing the Design Systems team directory. Access tokens refreshed successfully.',
    status: 'resolved',
    priority: 'low',
    category: 'access',
    creatorId: 'usr_emp_1',
    creatorName: 'Elena Rostova',
    creatorEmail: 'elena.rostova@acmecorp.com',
    assigneeId: 'usr_agent_2',
    assigneeName: 'Alex Rivera',
    slaDueHours: 48,
    slaDeadline: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    isOverdue: false,
    resolvedAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 26 * 3600 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    commentsCount: 4,
  },
];

export const RECENT_ACTIVITIES: ActivityItem[] = [];

export const LANDING_SHOWCASE_ACTIVITIES: ActivityItem[] = [
  {
    id: 'showcase-act-1',
    ticketId: 'demo-tkt-1',
    userId: 'usr_agent_2',
    userName: 'Alex Rivera',
    action: 'Changed status to In Progress',
    details: 'Investigating query planner stall on write replica',
    timestamp: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
  },
  {
    id: 'showcase-act-2',
    ticketId: 'demo-tkt-4',
    userId: 'usr_agent_2',
    userName: 'Alex Rivera',
    action: 'Resolved ticket',
    details: 'SCIM token refreshed, verified directory sync for 14 designers',
    timestamp: new Date(Date.now() - 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'showcase-act-3',
    ticketId: 'demo-tkt-3',
    userId: 'usr_agent_1',
    userName: 'Sarah Chen',
    action: 'Assigned to self',
    details: 'Asset tag #MBP-2026-99 allocated and imaging in progress',
    timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
  },
  {
    id: 'showcase-act-4',
    ticketId: 'demo-tkt-2',
    userId: 'usr_emp_1',
    userName: 'Elena Rostova',
    action: 'Created ticket',
    details: 'Reported VPN handshake timeout on macOS 15.3',
    timestamp: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
  },
];

export const DEMO_CHART_TREND = [
  { date: 'Mon', created: 12, resolved: 10 },
  { date: 'Tue', created: 15, resolved: 14 },
  { date: 'Wed', created: 18, resolved: 16 },
  { date: 'Thu', created: 14, resolved: 15 },
  { date: 'Fri', created: 20, resolved: 19 },
  { date: 'Sat', created: 8, resolved: 9 },
  { date: 'Sun', created: 5, resolved: 6 },
];

export const getFallbackMetrics = () => ({
  totalTickets: 0,
  openTickets: 0,
  inProgressTickets: 0,
  resolvedTickets: 0,
  overdueTickets: 0,
  avgResolutionTimeHours: 0,
  slaComplianceRate: 100,
  statusDistribution: [
    { status: 'open' as const, count: 0, label: 'Open' },
    { status: 'in_progress' as const, count: 0, label: 'In Progress' },
    { status: 'waiting' as const, count: 0, label: 'Waiting' },
    { status: 'resolved' as const, count: 0, label: 'Resolved' },
  ],
  priorityDistribution: [
    { priority: 'urgent' as const, count: 0, label: 'Urgent' },
    { priority: 'high' as const, count: 0, label: 'High' },
    { priority: 'medium' as const, count: 0, label: 'Medium' },
    { priority: 'low' as const, count: 0, label: 'Low' },
  ],
  categoryDistribution: [
    { category: 'hardware' as const, count: 0, label: 'Hardware' },
    { category: 'software' as const, count: 0, label: 'Software' },
    { category: 'network' as const, count: 0, label: 'Network' },
    { category: 'access' as const, count: 0, label: 'Access' },
    { category: 'security' as const, count: 0, label: 'Security' },
    { category: 'other' as const, count: 0, label: 'Other' },
  ],
  ticketsTrend: [
    { date: 'Mon', created: 0, resolved: 0 },
    { date: 'Tue', created: 0, resolved: 0 },
    { date: 'Wed', created: 0, resolved: 0 },
    { date: 'Thu', created: 0, resolved: 0 },
    { date: 'Fri', created: 0, resolved: 0 },
    { date: 'Sat', created: 0, resolved: 0 },
    { date: 'Sun', created: 0, resolved: 0 },
  ],
  recentActivity: RECENT_ACTIVITIES,
});
